### ISSUE TITLE
Some sections in "Server admin guide" and "Securing Apps guide" have references to Wildfly distribution

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak-documentation#1669]
### Describe the bug

- This section of admin guide https://www.keycloak.org/docs/19.0.1/server_admin/index.html#client-certificate-lookup contains instructions specific to Wildfly. This should be changed and updated for the steps specific to Quarkus distribution as we're removing Wildfly.

- The section of admin guide https://www.keycloak.org/docs/19.0.1/server_admin/#_mappers has reference to Wildfly configuration file (standalone.xml or domain.xml)

- The FAPI section of securing apps guide: https://www.keycloak.org/docs/latest/securing_apps/index.html#tls-considerations

### Version

19.0.1

**Comment by stianst** [comment]
@mposolda pretty sure all of these are already solved in main now. Could you check the docs from main and not 19.0 docs?

**Comment by mposolda** [comment]
@stianst Some of them were still present. Sent PR to update those parts: https://github.com/keycloak/keycloak-documentation/pull/1674
